name: Build Wheels

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Swig (macos-latest)
        if: matrix.os == 'macos-latest'
        run: brew install swig

      - name: Install Swig (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install swig

      - uses: actions/setup-python@v2
      
      - name: Install poetry
        run: python -m pip install poetry==1.1.12

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0

      - name: Build wheels
        env:
          CIBW_ARCHS: auto
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-*
        run: python -m cibuildwheel pkg/pypi --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl
